recipe/meta.yaml

bump to 0.2.11

---

recipe/meta.yaml

bump to 0.7.0

---

recipe/meta.yaml

Bump to v0.8.1

---

recipe/meta.yaml

add ipywidgets

---

recipe/meta.yaml

Bump version to 1.1.0

---

recipe/meta.yaml

Update to 1.5.0

---

recipe/meta.yaml

Bump to 1.6.0

---

recipe/meta.yaml

add pyarrow

---

.github/CODEOWNERS
README.md
recipe/meta.yaml

add @jbweston

---

.gitignore
.scripts/build_steps.sh
.scripts/run_docker_build.sh
recipe/meta.yaml

Restrict to the actual requirements and do not include optional requirements

---

recipe/meta.yaml

Bump to v2.3.0

---

.scripts/build_steps.sh
.scripts/run_osx_build.sh
build-locally.py
recipe/meta.yaml

Bump to 2.4.0

---

recipe/meta.yaml

Bump to v2.4.1

---

recipe/meta.yaml

Bump to 2.5.0

---

recipe/meta.yaml

Bump to 2.11.0

---

recipe/meta.yaml

Bump to 2.12.0

---

recipe/meta.yaml

Bump to 2.12.2

---

recipe/meta.yaml

Bump to adaptive-scheduler 2.13.2

---

recipe/meta.yaml

Bump to adaptive-scheduler 2.13.3

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_64_.yaml
build-locally.py
recipe/meta.yaml

Bump to adaptive-scheduler 2.14.0

---

recipe/meta.yaml

Bump to adaptive-scheduler 2.14.2

---

.scripts/build_steps.sh
.scripts/run_docker_build.sh
build-locally.py
pixi.toml
recipe/recipe.yaml

Bump to adaptive-scheduler 2.14.4

---

pixi.toml
recipe/recipe.yaml

Bump to adaptive-scheduler 2.14.5

---

recipe/recipe.yaml

Bump to adaptive-scheduler 2.14.13

---

recipe/recipe.yaml

Bump to adaptive-scheduler 2.14.14

---

recipe/recipe.yaml

Bump to adaptive-scheduler 2.15.0
